### ISSUE TITLE
Summary of backend needs analysis 

### ISSUE THREAD

**Issue by CarolineMorton** [opensafely/cohort-extractor#163]
- Implementation of Emergency Care Dataset (ECDS) to calculate number of A&E episodes in X time frame (similar to GP consultation rate)
    - Big table on schema but we will only need limited part of it, namely episode date
    - [Here](https://github.com/opensafely/outcomes-notebook/issues/3) is an issue about which fields we need 
- Care home 
  - I think this is done to an extent - we can see if someone is in a carehome and if that carehome is a nursing home, but I'm not sure we can return carehome ID. (though this might be negated by household ID - not sure.
- Household 
  - Two tables `Household` and `HouseholdMember`
  - Fields of interest are likely `HouseholdSize` and `Household_ID`
- Being coded with suspected or confirmed COVID in primary care 
- Being tested for COVID and testing positive for COVID 
- COVID-19 related hospital inpatient (?SUS data - currently not available although possibly requested)

**Comment by CarolineMorton** [comment]
1. ECDS: We want:
     - Date of attendance 
     - No of attendances in X period of time
     - COVID attendance (from codelist)
     - Discharge destination

2. Care home - need to check with Chris Bates as whether `Care home Id` and `household id` are likely to be the same in which case Care home id may not be needed as we have binary flag for care home or not. 

3. Household - fields are in the schema under Household table. In first instance, we would like to get info from Household_ID and Household_Size to create a numerical value for household_id and a numerical value for household size.
     - Ideally it would be great to be able to define age brackets or a read code list that outputs columns. For example, returns number of people in a defined group as a numerical value. This is likely to be easier to do in Stata but could be done one day in Python.

**Comment by sebbacon** [comment]
Thanks! @evansd is going to split this into individual issues

**Comment by inglesp** [comment]
I've added issues for the five non-done data sources.
