### ISSUE TITLE
Discuss measures / dashboards requirements

### ISSUE THREAD

**Issue by sebbacon** [opensafely/cohort-extractor#169]
@HelenCEBM is working on prototype code for dashboards.

We've written a spike to support a vaccination dashboard.

To incorporate this cleanly into the framework, we need to take a step back to understand the top-level requirements for this kind of output.  For example:

* What should a dashboard definition look like?
* What should the generated dataframe / CSV look like?
* What are the graphical / analytic outputs based on the dataframe(s)?
  * To whom will they be presented? Where?
* How often should dashboard be updated?
* What will the scale of dashboards be? (Number of measures, time frames, number of geographies, number of facets)
* What funding is in place for this? How much resource should be dedicated to it, compared with other projects?

Some notes about fine-grained requirements at https://github.com/opensafely/aftershocks-notebook/issues/12 and https://github.com/opensafely/aftershocks-notebook/issues/5

@sebbacon @evansd and @HelenCEBM to have a meeting to discuss.

**Comment by HelenCEBM** [comment]
Some general considerations for building measures are here: https://github.com/opensafely/aftershocks-notebook/issues/16

Very specific examples are now given in some detail here (though are not finalised):
https://github.com/opensafely/aftershocks-notebook/issues/5

> What should a dashboard definition look like? / What should the generated dataframe / CSV look like?

- The only way I can imagine making them generalisable is through something much like our current study definition, but run every month, building in the additional constraints as set out in issue 16 linked above. However this would give many dataframes. 

> How often should dashboard be updated?

- I'm generally working on an assumption of "monthly" but in some cases weekly would be useful

> What will the scale of dashboards be? (Number of measures, time frames, number of geographies, number of facets) 

- Highly variable! But broadly, (a) National dashboards (practice deciles, totals, regional highlights etc) running outside of secure environment; (b) Practice dashboards, to be prototyped by us but implemented within EHR providers for GPs eventually; and (c) Some regional dashboards (e.g. CCG), details tbc.

**Comment by sebbacon** [comment]
Closed for #343
