### ISSUE TITLE
Add ability to pin cohort-extractor version

### ISSUE THREAD

**Issue by sebbacon** [opensafely/cohort-extractor#174]
Current thoughts are either in `requirements.txt` or in the proposed project config file (#172).

This should be respected by any github workflow actions

**Comment by evansd** [comment]
I was thinking that study definitions ought to include a format version number, which could just be the release version of the cohort-extractor which was current at the time of writing. This could be used to automatically apply backwards compatibility fixes to study definitions. And to prevent trying to run a newer format study with an old version of the software.

I think `requirements.txt` feel like the wrong approach now. The study repo isn't (or shouldn't be) telling the executing infrastructure what to install.

**Comment by sebbacon** [comment]
Currently the project config file provides a way to specify a version; we'll stick with that for now
