### ISSUE TITLE
Add household data to backend

### ISSUE THREAD

**Issue by inglesp** [opensafely/cohort-extractor#183]
Split out from https://github.com/opensafely/cohort-extractor/issues/163.

> Fields are in the schema under Household table. In first instance, we would like to get info from Household_ID and Household_Size to create a numerical value for household_id and a numerical value for household size.
> 
> Ideally it would be great to be able to define age brackets or a read code list that outputs columns. For example, returns number of people in a defined group as a numerical value. This is likely to be easier to do in Stata but could be done one day in Python.
>

**Comment by inglesp** [comment]
The first part of this was done in #177.  We now support:

* `patients.household_as_of("2020-02-01", returning="pseudo_id")`
* `patients.household_as_of("2020-02-01", returning="household_size")`

**Comment by sebbacon** [comment]
https://github.com/opensafely/cohort-extractor/issues/372 proposes:

```python
 household_id=patients.household_as_of(
     "2020-02-01", returning="household", method="UPRN"
 )
```

This would probably add something like

```python
 household_id=patients.household_as_of(
     "2020-02-01", returning="household_size", age_constraint="age > 16"
 )
```

However, I'm going to close this because I think it's low priority, and a very custom thing for specific studies that is unlikely to get implemented in other backends for a while
