### ISSUE TITLE
Add inpatient data from SUS to backend

### ISSUE THREAD

**Issue by inglesp** [opensafely/cohort-extractor#186]
Split out from https://github.com/opensafely/cohort-extractor/issues/163.

> has been requested and may arrive at some point

**Comment by inglesp** [comment]
@CarolineMorton @alexwalkercebm @brianmackenna What should the API look like here? What kinds of questions will you want to ask of the SUS data?

**Comment by CarolineMorton** [comment]
I haven't yet seen a schema of what is available. I am not sure if it includes diagnostic codes / reasons for admissions. 

i think what we want would be something like:

```
admission = patients.admitted_to_hospital(
    on_or_after='2020-02-01",
    returning="date_admitted",
    find_first_match_in_period=True,
    include_discharge_date=True
    )
```

If it was possible, we might want a diagnostic code:

```
admission = patients.admitted_to_hospital_with_diagnosis(
    codelist,
    on_or_after='2020-02-01",
    returning="date_admitted",
    find_first_match_in_period=True,
    include_discharge_date=True
    )
```

**Comment by CarolineMorton** [comment]
@HelenCEBM would have a view im sure as it would be good to also fit with aftershocks work

**Comment by HelenCEBM** [comment]
I've used SUS a lot before, though I don't know if we'll have access to all of the fields or not. 

- Biggest thing that springs to mind is that we will want to distinguish emergency (non-elective) from planned (elective) admissions, as we will typically only want the unplanned ones (except for aftershocks). (There's also "non-elective non-emergency" which is usually maternity we probably want to exclude).
- There should be plenty of diagnosis codes and procedure codes to choose from. The HRG can be useful if present. The specialty code might help distinguish relevant admissions (though there are usually two specialties, one may be that of the admitting consultant which could be unrelated e.g. depending upon which consultant happened to be on duty in A&E). 
- "Spells" in hospital may be split into "episodes" under different consultants/wards as patients sometimes move around, so want to avoid double counting these. Presume the data will arrive split out like this, but there should be an original admission date and ultimate discharge date in each row.
- There will (presumably) be rows of unfinished episodes where the patient is still in hospital at the end of the reporting month, i.e. the discharge date will be null in these cases unless we choose to exclude them.

**Comment by krishnanbhaskaran** [comment]
For some studies we might want to use COVID-related hospital admission as an outcome, in which case we'd want to pull the first hospital admission with a COVID-related diagnosis code; perhaps returning the date and the code? 

From using HES previously, I think you may get a "primary" diagnosis and then a full list of diagnoses, per hospitalisation, and so it would be good to be able to specify in study def's whether you just want hospitalisations where COVID was the primary diagnoses, or hospitalisations where COVID was coded anywhere.

Another key use of the dataset will be to pick up comorbidity history - e.g. ever hospitalised for myocardial infarction (or whatever) prior to the study start date.

**Comment by rohinimathur** [comment]
Agree with @krishnanbhaskaran that for many studies we will want to separate hospital admission into COVID/non-COVID related - both as an outcome of interest and to define hopsital based denominator populations.
If possible we may still want to see all diagnosis codes in case people are admitted for respiratory conditions which may be COVID related.

**Comment by HelenCEBM** [comment]
We will have the primary and other diagnosis codes to use as needed - the fields we requested are in [this folder](https://drive.google.com/drive/u/1/folders/1bLuK1wux77tf7pTrguxsRthBMAO1FitV)

**Comment by inglesp** [comment]
I'm going to need some help from somebody who understands the data.  There are samples of dummy data for each table we have access to in [this notebook](https://github.com/ebmdatalab/tpp-sql-notebook/blob/master/notebooks/tpp-schema.ipynb).

There are references to SUS in the following tables:

* APCS
  * Spell_Core_HRG_SUS 
  * Spell_HRG_Version_No_SUS 
* CPNS
  * Der_Latest_SUS_Attendance_Date_For_Ethnicity
* EC
  * SUS_HRG_Code
  * SUS_Tariff
  * SUS_Final_Price

None of these fields look very useful!

So to start us off, could someone help me work out what kind of query I'd need to do to answer the question:

> Given the SNOMED code of a diagnosis, which patients have been admitted with that diagnosis?

**Comment by sebbacon** [comment]
@wjchulme, can you help?

**Comment by HelenCEBM** [comment]
@inglesp those fields look like the ones in tables we have to join on to the main tables. Can you list all of the fields from those tables? Whether there is the word SUS in the fields or not is irrelevant, those three tables are all SUS

**Comment by alexwalkercebm** [comment]
Regrading the SNOMED question, diagnoses codes will be recorded in ICD10 rather than SNOMED. I think the relevant field for this is `Der_Diagnosis_All`, which seems to contain a comma separated list of ICD10 codes.

**Comment by krishnanbhaskaran** [comment]
Yes I would expect it to be ICD10 rather than SNOMED. In HES you generally get "all diagnosis codes in the hospitalisation" and then a single "primary diagnosis for the hospitalisation" - and researchers may want to access one or both of these in study def's.

I can't access the notebook you linked to above Peter - do I need to be given access?

Happy to look at any fields/dummy data to try and help with this. I'm familiar with HES which I think is similar.

**Comment by inglesp** [comment]
Here's the full list of fields from those tables:
* APCS
  * Patient_ID 
  * APCS_Ident 
  * Carer_Support_Indicator 
  * Ethnic_Group 
  * Administrative_Category 
  * Patient_Classification 
  * Admission_Method 
  * Discharge_Destination 
  * Discharge_Method 
  * Source_of_Admission 
  * Admission_Date 
  * Discharge_Date 
  * Provider_Org_Code_Type 
  * Duration_of_Elective_Wait 
  * Spell_Core_HRG_SUS 
  * Spell_HRG_Version_No_SUS 
  * Hospital_Spell_Duration 
  * Der_Spell_LoS 
  * Der_Diagnosis_Count 
  * Der_Procedure_Count 
  * Der_Diagnosis_All 
  * Der_Procedure_All 
  * Der_Admit_Treatment_Function_Code 
  * Der_Dischg_Treatment_Function_Code 
  * Der_Pseudo_Patient_Pathway_ID 
  * Der_Activity_Month 
  * Der_Financial_Year
* CPNS
  * Patient_ID 
  * Id 
  * LocationOfDeath 
  * Sex 
  * DateOfAdmission 
  * DateOfSwabbed 
  * DateOfResult 
  * RelativesAware 
  * TravelHistory 
  * RegionCode 
  * RegionName 
  * OrganisationTypeLot 
  * RegionApproved 
  * RegionalApprovedDate 
  * NationalApproved 
  * NationalApprovedDate 
  * PreExistingCondition 
  * Age 
  * DateOfDeath 
  * HadLearningDisability 
  * ReceivedTreatmentForMentalHealth 
  * Der_Ethnic_Category_Description 
  * Der_Latest_SUS_Attendance_Date_For_Ethnicity 
  * Der_Source_Dataset_For_Ethnicty 
  * snapDate 
  * OnDeathCertificateNotice 
  * CovidTestResult 
  * NHSworker 
  * PreExistingConditionList 
  * LearningDisabilityType 
  * TransferredFromLearningDisabilityAutismSetting 
  * TransferredFromAMentalHealthSetting 
  * DetainedUnderMHAct
* EC
  * Patient_ID 
  * EC_Ident 
  * Ethnic_Category 
  * EC_Department_Type 
  * Arrival_Date 
  * Arrival_Time 
  * EC_Arrival_Mode_SNOMED_CT 
  * EC_AttendanceCategory 
  * EC_Attendance_Source_SNOMED_CT 
  * EC_Decision_To_Admit_Date 
  * Decision_To_Admit_Treatment_Function_Code 
  * Discharge_Destination_SNOMED_CT 
  * EC_Chief_Complaint_SNOMED_CT 
  * EC_Injury_Date 
  * SUS_HRG_Code 
  * SUS_Tariff 
  * SUS_Final_Price 
  * DQ_Chief_Complaint_Expected 
  * DQ_Chief_Complaint_Completed 
  * DQ_Chief_Complaint_Valid 
  * DQ_Primary_Diagnosis_Expected 
  * DQ_Primary_Diagnosis_Completed 
  * DQ_Primary_Diagnosis_Valid 
  * Der_EC_Diagnosis_All 
  * Der_EC_Investigation_All 
  * Der_EC_Treatment_All 
  * Der_Activity_Month 
  * Der_Financial_Year

**Comment by HelenCEBM** [comment]
Just to clarify, the APCS is inpatient data (Admitted Patient Care Spells). CPNS is the deaths table (not part of SUS) and EC is Emergency Care (A&E - replacement for old ECDS table). So APCS is the one relevant to this issue.

**Comment by krishnanbhaskaran** [comment]
Looking at the notebook, I suspect the key fields for the sorts of uses I am thinking of are:

APCS: 
Admission date
Discharge date
Der_Diagnosis_All (icd codes)
Der_Procedure_All (opcs codes?)
Ethnic_Group

APCS_Der
Spell_primary_diagnosis (icd code)
Spell_secondary_diagnosis (icd code)

Some examples of how these might be used...

To identify covid hospitalisations as an outcome (e.g. HIV study) we might want 
- the earliest admission date with a COVID-19 ICD-10 code (defined in a code list) in Der_Diagnosis_All
- perhaps with an overall date restriction (e.g. only counting admissions after 1/3/2020)
- or for a more stringent definition, the earliest admission date with a COVID-19 ICD-10 code in Spell_primary_diagnosis (where primary diagnosis is interpreted as the "main reason" for hospitalisation).
- one might also specify an intermediate definition where the codes of interest are in "Spell_primary_diagnosis" OR "Spell_secondary_diagnosis"
- study def should be able to return the relevant admission date and the matched code, if needed
- might also want to return the discharge date (if interested in length of the hospitalisation)

We might also want to use hospital admissions data to pick up comorbidities that may have been missed in the primary care data. E.g. a proportion of MIs are missed if you only use primary care codes. e.g.
- the earliest admission date with an ICD-10 code for MI (from a defined code list ) in Der_Diagnosis_All
- perhaps with an overall date restriction (e.g. only counting admissions before 1/3/2020)

The procedure codes field might also be needed - e.g. proportion of people with previous surgery for X would be: 
- the earliest admission date with an OPCS code for the relevant surgery in Der_Procudure_All

If you were looking at follow-up AFTER a COVID-19 admission you might want a query based on discharge date, e.g.
- the first/last DISCHARGE date with a COVID-19 ICD-10 code in Der_Diagnosis_All


Also, users may want to also return ethnic_group from the SUS record in some of these queries because it is generally more complete than in primary care.

**Comment by inglesp** [comment]
This is really helpful, thanks @krishnanbhaskaran.

Building on @CarolineMorton's suggestions [here](https://github.com/opensafely/cohort-extractor/issues/186#issuecomment-647525230), and the [`attended_emergency_care()` API](https://github.com/opensafely/cohort-extractor/blob/master/cohortextractor/patients.py#L563-L589), here's a proposal for an API that lets you answer your questions.

```
patients.admitted_to_hospital(
    returning="binary_flag" | "date_admitted" | "date_discharged" | "primary_diagnosis",  # defaults to "binary_flag"
    with_these_diagnoses=codelist,  # optional
    with_these_primary_diagnoses=codelist,  # optional
    on_or_before=date,  # optional
    on_or_after=date,  # optional
    between=date,  # optional
    find_first_match_in_period=bool,  # optional
    find_last_match_in_period=bool,  # optional
    date_format="YYYY" | "YYYY-MM" | "YYYY-MM-DD",  # optional
)
```

And here's how you would use the API to answer your questions:

> the earliest admission date with a COVID-19 ICD-10 code

```
patients.admitted_to_hospital(
    returning="date_admitted",
    find_first_match_in_period=True,  # no period is specified, so we include all spells/episodes
    with_these_diagnoses=[...],
)
```

> perhaps with an overall date restriction (e.g. only counting admissions after 1/3/2020)

```
patients.admitted_to_hospital(
    returning="date_admitted",
    on_or_after="2020-03-01",
    find_first_match_in_period=True,
    with_these_diagnoses=[...],
)
```

> the earliest admission date with a COVID-19 ICD-10 code in Spell_primary_diagnosis

```
patients.admitted_to_hospital(
    returning="date_admitted",
    find_first_match_in_period=True,
    with_these_primary_diagnosis=[...],  # should this name be explicit about being primary diagnosis for a spell vs episode?
)
```

> study def should be able to return the relevant admission date and the matched code, if needed

Admission date covered above.

```
patients.admitted_to_hospital(
    returning="primary_diagnosis",  # would we be interested in other diagnoses?
    find_first_match_in_period=True,
)
```

> might also want to return the discharge date

```
patients.admitted_to_hospital(
    returning="date_discharged",
    find_first_match_in_period=True,
)
```

> the earliest admission date with an ICD-10 code for MI

Covered above.

> the earliest admission date with an OPCS code for the relevant surgery

```
patients.admitted_to_hospital(
    returning="date_admitted",
    find_first_match_in_period=True,
    with_these_procedures=[...],  # or should this be with_these_surgical_procedures
)
```

> the first/last DISCHARGE date with a COVID-19 ICD-10 code in Der_Diagnosis_All


```
patients.admitted_to_hospital(
    returning="discharge_date",
    find_last_match_in_period=True,
    with_these_diagnoses=[...],
)
```

What do you think?

**Comment by inglesp** [comment]
> Just to clarify, the APCS is inpatient data (Admitted Patient Care Spells). CPNS is the deaths table (not part of SUS) and EC is Emergency Care (A&E - replacement for old ECDS table). So APCS is the one relevant to this issue.

Very useful, thanks @HelenCEBM!

**Comment by krishnanbhaskaran** [comment]
@inglesp 

This looks great!

A few Qs (some/all may just be revealing my tech illiteracy!)...

- First,  a minor point - just to note that "with_these_procedures" was not in the proposed api but it is in the examples.

- Can more than one thing in the "returning" list be returned as separate columns?. e.g. might want to return both date admitted AND primary_diagnosis. Or date admitted AND date discharged (e.g. for studies involving length of hospitalisation), etc?

- How would we specify whether the part of the search involving dates (e.g. "on_or_after" etc) should be done on the basis of the admission date, or the discharge date? Different studies may need different things. Is this determined by whether you set "returning" to date_admitted or date_discharged? But what if you want to return both dates of admission and discharge?

- If we have searched on "all" diagnoses (with_these_diagnoses) I wonder if it would be possible to return the code(s) that matched from the Der_Diagnosis_All field? As it is, if we can only return the "primary_diagnosis" this may be different to the code(s) that actually matched against our codelist. Returning the matching codes has been useful for debugging codelists in primary care (e.g. it is how we diagnosed the error in the HIV codelist).

- On the queries in the post above:
> with_these_primary_diagnosis=[...],  # should this name be explicit about being primary diagnosis for a spell vs episode?
As far as I understand we don't have the data split into "episodes" and we only have spells (hospitalisations) - if that's right then it will always be the primary diagnosis for the full spell so name prob ok - though I guess if there is a chance that we may get data broken down into episodes in the future then it wouldn't hurt to be more specific.

> returning="primary_diagnosis",  # would we be interested in other diagnoses?
Possibly - see my 4th bullet point above

>    with_these_procedures=[...],  # or should this be with_these_surgical_procedures
I think it could cover more than surgery so would leave it more general

**Comment by inglesp** [comment]
> First, a minor point - just to note that "with_these_procedures" was not in the proposed api but it is in the examples.

Well spotted.  I'll update it.

> Can more than one thing in the "returning" list be returned as separate columns?. e.g. might want to return both date admitted AND primary_diagnosis. Or date admitted AND date discharged (e.g. for studies involving length of hospitalisation), etc?

No, the framework doesn't support that at the moment.  If you wanted both `date_admitted` and `primary_diagnosis`, you'll need to do something like:

```
StudyDefinition(
    hospital_date_admitted=patients.admitted_to_hospital(
        returning="date_admitted",
        find_first_match_in_period=True,
    ),
    hospital_primary_diagnosis=patients.admitted_to_hospital(
        returning="primary_diagnosis",
        find_first_match_in_period=True,
    )
)
```

To get both `date_admitted` and `date_discharged` you'd have to do the same.  (But we'll have to be careful in the backend to ensure that both dates correspond to the same episode.)

> How would we specify whether the part of the search involving dates (e.g. "on_or_after" etc) should be done on the basis of the admission date, or the discharge date? Different studies may need different things. Is this determined by whether you set "returning" to date_admitted or date_discharged? But what if you want to return both dates of admission and discharge?

This is a very good question.  For ICNARC (`patients.admitted_to_icu`) we always use the admission date, even though a discharge date is available.

We could make it so that `on_or_after` etc was applied to what was being returned, but then you wouldn't be able to compute length of stay, because if a patient is already in hospital at the start the period and is then discharged and readmitted again in the period, the first discharge will be before the first admission.

What would you lose if we matched ICNARC and only supported filtering on admission date?

> If we have searched on "all" diagnoses (with_these_diagnoses) I wonder if it would be possible to return the code(s) that matched from the Der_Diagnosis_All field? As it is, if we can only return the "primary_diagnosis" this may be different to the code(s) that actually matched against our codelist. Returning the matching codes has been useful for debugging codelists in primary care (e.g. it is how we diagnosed the error in the HIV codelist). Similarly - may want to return the matching procedure code(s) if the search was done based on procedures.

We can provide a comma-separated list of codes that appear in either the primary diagnosis, the secondary diagnosis, or `Der_Diagnosis_All`

How about:

```
patients.admitted_to_hospital(
    returning="matching_diagnoses",
    with_these_diagnoses=[...],
)
```

(And the same for procedures.)

> Can ethnic group be returned?

Yes!  Sorry, you mentioned this earlier in the thread.  Will update the proposal.

**Comment by krishnanbhaskaran** [comment]
>No, the framework doesn't support that at the moment. If you wanted both date_admitted and primary_diagnosis, you'll need to do something like:
StudyDefinition(
    hospital_date_admitted=patients.admitted_to_hospital(
        returning="date_admitted",
        find_first_match_in_period=True,
    ),
    hospital_primary_diagnosis=patients.admitted_to_hospital(
        returning="primary_diagnosis",
        find_first_match_in_period=True,
    )
)
To get both date_admitted and date_discharged you'd have to do the same. (But we'll have to be careful in the backend to ensure that both dates correspond to the same episode.)

That seems fine as a workaround

>What would you lose if we matched ICNARC and only supported filtering on admission date?

I think that filtering on admission date will be the priority and most common thing that people will want. I don't have any immediate application for filtering on discharge date, but it might become something that is needed later if we do studies on outcomes post-hospital discharge. But I suppose you could work around it by grabbing all potentially relevant spells based on admissions, returning the discharge date, and then filtering further in Stata... So yes I would say filtering on admission date only is probably workable.

>We can provide a comma-separated list of codes that appear in either the primary diagnosis, the secondary diagnosis, or Der_Diagnosis_All
How about:
patients.admitted_to_hospital(
    returning="matching_diagnoses",
    with_these_diagnoses=[...],
)
(And the same for procedures.)

Yes, that seems perfect.

**Comment by wjchulme** [comment]
If we want to return ethnicity would it be better to use a standalone function? Returning information that doesn't directly relate to the actual admission feels conceptually different than getting info about the admission itself. And there may be a challenge with potentially conflicting ethnicity information in the same patient over different spells. I don't think it's vanishly rare (though @krishnanbhaskaran @HelenCEBM may know better) so it may be helpful to have a function that exposes and/or resolves those issues.

So it would be something like

    patients.admitted_to_hospital_ethnicity(
      find_most_recent_nonmissing_in_period=True, # or maybe this should always happen so not an option
      return_null_if_conflict = True, # if there are at least two non-null values that don't match
      on_or_before=date,  # optional
      on_or_after=date,  # optional
      between=date,  # optional
    )

In general you'd want to do this when supplementing missing primary care data with any info that is only available for those with a recent appearence in an external dataset, whether it's ethnicity, comorbidities, any other incidental info (also warning: this will introduce odd and messy non-randomness in the missing data structure!). Using something like:

    patients.admitted_to_hospital_characteristics(
      returning = "ethnicity" | "MI_history" | "stroke_history" | ..., #whatever the external dataset has
      find_most_recent_nonmissing_in_period=True, # or maybe this should always happen so not an option
      return_null_if_conflict = True, # if there are two non-null values that don't match
      on_or_before=date,  # optional
      on_or_after=date,  # optional
      between=date,  # optional
    )

**Comment by krishnanbhaskaran** [comment]
@rohinimathur knows the most about the ethnicity issue. I don't think any problem if it was a separate function. In general it's going to be most useful for studies that only include hospitalised patients - otherwise as Will notes the randomness is non-random and dependent on hospitalisation.

**Comment by krishnanbhaskaran** [comment]
But comorbidities are different - comorbidity "history" is not recorded within a hospitalisation. We need to directly look for relevant historical admissions. So I think it is best handled as in the original proposal.

**Comment by wjchulme** [comment]
@krishnanbhaskaran sorry yes I meant in the hypothetical case of an external dataset where we want to return incidental information not relating to the events being described in that dataset, for the purpose of supplementing primary care data (or something else). The concrete case here is ethnicity in APNS but it could be any variable in any dataset in future. I've edited second code chunk above to clarify.

The point remains about wanting supplementary ethnicity information that may not be present in the specific admission of interest (eg becasue it's missing for that admission but not for a previous admission). And the need to resolve inconsistencies. So I think still worth separating out.

**Comment by inglesp** [comment]
OK, I'll remove "ethnicity" as an allowed value for the returning argument.

@krishnanbhaskaran will you need something like `patients.admitted_to_hospital_ethnicity` in the near future?

**Comment by krishnanbhaskaran** [comment]
@inglesp a function to pull ethnicity from hospital data might be useful at some point but is not urgent one from my perspective.

**Comment by HelenCEBM** [comment]
It might be useful to run a check on how many patients with missing ethnicity in primary care we can complete using their inpatient records. If tiny we might be able to drop it altogether.

**Comment by krishnanbhaskaran** [comment]
@rohinimathur has looked at this for CPRD and it did substantially improve completeness among those with hospitalisation records https://pubmed.ncbi.nlm.nih.gov/24323951/ - though this may now be a bit out of date.

**Comment by HelenCEBM** [comment]
Thoughts on discharge dates:
- It might be worth checking whether or not we only have completed spells (ie. patient has been discharged) - we might need an optional filter on there being a discharge date present as data relating to unfinished spells will be incomplete. Could be done in Stata though. 
- I think for the care homes project it will be important to look at when patients are discharged from hospitals to care homes. However, it wouldn't be ideal to only include one discharge record per patient so perhaps that will need more thinking / a different strategy anyhow. cc @rozeggo

**Comment by rohinimathur** [comment]
Agree with @krishnanbhaskaran that HES ethnicity will likely boost the completeness of ethnicity significantly.- though would need careful consideration about who is admitted to hospital and what biases this may introduce when using HES ethnicity to supplement TPP ethnicity.
 Also @wjchulme agree that being able to extract ethnicity as a separate function would work well.

**Comment by krishnanbhaskaran** [comment]
Just a thought that occured to me on on how ICD-10 codelists should be specified... the codes typically have a letter and two numbers for the main category of diagnosis - e.g. "C34" for lung cancer, and then (sometimes) extra characters that are more specific, e.g. 

C34.0 Main bronchus
C34.1 Upper lobe, bronchus or lung
C34.2 Middle lobe, bronchus or lung
C34.3 Lower lobe, bronchus or lung
C34.8 Overlapping lesion of bronchus and lung
C34.9 Bronchus or lung, unspecified

Sometimes even more characters may be specified, signifying extra clinical detail (that will generally be of limited interest).

We'd often just want all sub-codes (and if potentially several levels of detail beyond the first 3 characters, it would be difficult to exhaustively specify every possible sub-code), so ... the ideal would be that we can specify codes up to the level of detail required, and the back end would automatically search for all sub-codes. E.g., for all lung cancers the code list would just need to say C34 (or alternatively C34*) and this would automatically search for all codes _beginning with_ C34 - is that possible?

A related thing is that I noticed in your example row (posted on Slack) a code of C61X. C61 is prostate cancer, which has no sub-codes and it looks like in the data this appears with a meaningless X at the 4th character. Again, in terms of the codelist that we feed to the API, what we'd ideally want is to just specify "C61" and assume that it will pick up anything starting with C61.

**Comment by inglesp** [comment]
I've broken out #256 to track the work understanding `Diagnosis_Der_All`.
