### ISSUE TITLE
pyodbc should be an optional dependency

### ISSUE THREAD

**Issue by evansd** [opensafely/cohort-extractor#208]
Copied from Slack:

> I'm a bit confused now. I've just merged a PR to remove a dependency on pyodbc which I thought was causing people problems (https://github.com/opensafely/cohort-extractor/pull/207)
> But now I see that pip installing opensafely-cohort-extractor pulls in pyodbc anyway and has done for some time (https://github.com/opensafely/cohort-extractor/blame/master/setup.py)
> So now I don't understand how it worked before.

> I guess we want to make it an optional dependency so that `pip install opensafely-cohort-extractor[tpp]` pulls it in, but it doesn't install by default

**Comment by sebbacon** [comment]
It worked before because it was installed but not imported, I'd have thought? What am I not understanding? :)

**Comment by evansd** [comment]
Ah, mystery solved! Pyodbc [provides wheels](https://github.com/mkleehammer/pyodbc/wiki/Install) for OSX and Windows so it installs on those platforms without error, while on Linux it compiles from source and so requires unixodbc headers (which is why it failed to install when I tested it locally).

However although it _installs_ without throwing an error on OSX/Windows it will fail at import time unless you have an appropriate C++ compiler installed.

I was previously under the impression that the `unixodbc-dev` package had to be obtained from a Microsoft PPA, but it now appears that it's in the standard Ubuntu repos and so I'm a bit more relaxed about requiring it.

But still, I think it would be a nicer user experience if we didn't require it, and installing a package on OSX/Win that will probably not work isn't ideal either. So I think I'll leave this ticket open, although as a nice-to-have rather than something urgent.

**Comment by sebbacon** [comment]
@evansd can we close this?

**Comment by sebbacon** [comment]
Reopen if you disagree!
