### ISSUE TITLE
cohort_report failure

### ISSUE THREAD

**Issue by inglesp** [opensafely/cohort-extractor#219]
@alexwalkercebm has run `cohort_report` against the results of [this study])https://github.com/opensafely/codelist-prevalence-research/blob/257fcad4afc1d1cb99355c7937fa81330dbf1687/analysis/study_definition.py).

It generated the following error:

![image](https://user-images.githubusercontent.com/28734/86121058-46f8e480-bacd-11ea-8809-c5f61fdafb83.png)

The exception is:

```
pandas.errors.ParserError: Error tokenizing data. C error: Expected 5 fields in line 54291, saw 94
```

I have tried to reproduce locally, by running:

```
$ cohortextractor generate_cohort --expectations-population 10000
$ cp output/input.csv analysis/
$ cohortextractor cohort_report
```

and this works fine.

We expect the input to have 94 columns.  From code-reading, it looks like Pandas expects the CSV file that it's parsing to have the same number of columns in each row.  So why would the first 54290 rows have 5 columns?

**Comment by sebbacon** [comment]
We've worked this out. It's old error data which shouldn't be around, because of #220
