### ISSUE TITLE
Add R support

### ISSUE THREAD

**Issue by sebbacon** [opensafely/cohort-extractor#227]
This requires:
* Framework for executing safely in remote environment (docker image + #172 + runner support)
* Guidelines for package management
  * [renv local sources](https://rstudio.github.io/renv/articles/local-sources.html) might be the way to go here
  * But we should also assemble a list of common base packages that are pre-installed to reduce code review overhead

**Comment by sebbacon** [comment]
The simplest, initial approach is to permit a fixed list of libraries at known revisions, via a docker image, which will just install packages like `RUN Rscript -e 'install.packages(...)'`, ensuring these are from https://cran.r-project.org/.

The problem with this approach is it won't allow pinning of specific versions in particular repos.

Recent versions of R [can use packages as of a given date](https://blog.rstudio.com/2020/07/01/announcing-public-package-manager/) via [Package Manager](https://packagemanager.rstudio.com/client/#/repos/1/overview).  We could investigate requiring a pinned, old revision of the entire repo, but it would be simpler to bake everything into the docker image.

We could require that users pin an entire R environment to a docker specific docker image; this means they won't be able to mix-and-match versions, but might be good enough for the time being.

There is also an option to install our own Package Manager, which in addition to [repository checkpointing](https://packagemanager.rstudio.com/__docs__/admin/repositories/#repo-versions), can provide [a curated CRAN source](https://packagemanager.rstudio.com/__docs__/admin/repositories/#curated-cran-source). This will allow supported, pinned versions to be managed, added to etc, apparently with a reasonable workflow for upgrade paths, but does require commercial licensing.

**Comment by rozeggo** [comment]
data.table, matrixStats, plotrix, magrittr, lubridate, tidyverse, stringr, DBI, dplyr, zoo, stats

**Comment by esnightingale** [comment]
also possibly dtplyr, mgcv

**Comment by johntaz** [comment]
Survival

**Comment by wjchulme** [comment]
based on what I think may be popular

general: everything in the tidyverse (which includes lots of packages mentioned above and possibly some below)
utility: here, tictoc, janitor, naniar
modeling/stats: mice, lme4, nlme, relsurv, Hmisc, brms, binom
visualisation: cowplot, GGally, ggdist
sql: DBI
spatial: sp, maptools, rgeos, rgdal
parallelisation: doParallel, foreach, furrr, parallel

**Comment by esnightingale** [comment]
I think sf has superseded sp now? Also I use patchwork over cowplot but that's just personal preference :)

**Comment by wjchulme** [comment]
@esnightingale yes, you're right! edited

**Comment by esnightingale** [comment]
Might be too late now but sandwich also!

**Comment by sebbacon** [comment]
We now have rudimentary support. It needs improving but that can get its own issue
