### ISSUE TITLE
Version bumping not working

### ISSUE THREAD

**Issue by sebbacon** [opensafely/cohort-extractor#232]
Despite #179 appearing to work when testing, releases are not being generated as expected.

[Here](https://github.com/opensafely/cohort-extractor/runs/842107296?check_suite_focus=true) is a run that does not consider this a release. This appears to be because the merge commit does not include the relevant conventional commit type - i.e. it only seems to be considering the merge commit.

![image](https://user-images.githubusercontent.com/211271/86611752-073b6c80-bfa7-11ea-9efe-2dc3f55a9320.png)

However, [the documentation](https://github.com/marketplace/actions/github-tag#bumping) makes it clear that:

> The action will parse the new commits since the last tag using the semantic-release conventions

However, the last tag, v0.1.29, is at commit 49aadc23e8392ea85ec5e7522451daa946294130, since when there have been *two* commits starting `fix:`.

The command that the build linked to above runs is:

    git log v0.1.29..HEAD --pretty=format:'%s%n%b|commit-hash:%h==============================================' --abbrev-commit

And its output on `master` for me is:

```sh
$ git log v0.1.29..HEAD --pretty=format:'%s%n%b|commit-hash:%h==============================================' --abbrev-commit
Merge pull request #231 from opensafely/test-release-making
Tweak docs and in doing so test release-making|commit-hash:99bb748==============================================
fix: remove broken reference to roadmap in docs
This is not really a `fix`, but I want to test triggering a new release.
|commit-hash:c9bb852==============================================
Merge pull request #230 from opensafely/semantic-autoversioning
fix: use semantic versioning automation|commit-hash:718d063==============================================
Merge branch 'master' into semantic-autoversioning
|commit-hash:74ff162==============================================
docs: bring description of release process up to date
|commit-hash:08b8304==============================================
fix: use semantic versioning automation
This is not really a fix, but we do want to trigger a new release.

Closes #179
|commit-hash:6581bf0==============================================
```

Given the run log ends

```
Tweak docs and in doing so test release-making
The commit should not trigger a release
Analysis of 1 commits complete: no release
```

It seems odd that it should consider an analysis of 1 commit to be complete.

**Comment by sebbacon** [comment]
There is [an issue reporting the same problem for the action here](https://github.com/mathieudutour/github-tag-action/issues/18)

**Comment by sebbacon** [comment]
I presume the bug is in [this underlying library](https://github.com/semantic-release/commit-analyzer/). I suspect [this bug](https://github.com/semantic-release/commit-analyzer/issues/175) because our merge commits contain slashes.

**Comment by sebbacon** [comment]
And in turn I suspect the bug is in [this subpackage](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-commits-filter)

**Comment by sebbacon** [comment]
(just making notes as I think about this)

I wonder if the extra single quotes are messing with the line separator logic:

https://github.com/mathieudutour/github-tag-action/blob/76537e6a66e59ef3f78161c49d9cc1fbc597df3a/src/main.ts#L97-L100

**Comment by sebbacon** [comment]
The problem is that the current version of the `checkout` action checks the code out without any history (`depth=1`)

**Comment by inglesp** [comment]
> The problem is that the current version of the checkout action checks the code out without any history (`depth=1`)

Well done for getting to the bottom of that!
