### ISSUE TITLE
Hydroxychloroquine repo extract error

### ISSUE THREAD

**Issue by alexwalkercebm** [opensafely/cohort-extractor#235]
When running this repo https://github.com/opensafely/hydroxychloroquine-research on the server we get an error:
```Conversion failed when converting date and/or time from character string.```

It's passing tests, but same error occurs locally running `cohortextractor generate_cohort --database-url mssql+pyodbc://SA:ahsjdkaJAMSHDA123%5B@covid.ebmdatalab.net:1433/OpenCoronaExport?driver=ODBC+Driver+17+for+SQL+Server`

**Comment by inglesp** [comment]
I *think* the problem's that `"today"` is not a valid argument argument for the `on_or_before` parameter.  See https://github.com/opensafely/hydroxychloroquine-research/blob/master/analysis/study_definition.py#L66.

**Comment by alexwalkercebm** [comment]
It was indeed that, fixed by https://github.com/opensafely/hydroxychloroquine-research/pull/23
