### ISSUE TITLE
Should we continue to accept "today" as a valid date?

### ISSUE THREAD

**Issue by evansd** [opensafely/cohort-extractor#237]
Currently we handle it in a few specific arguments:
https://github.com/opensafely/cohort-extractor/blob/1d3d53545c1eb06caad3ed4993eb483907417062/cohortextractor/process_covariate_definitions.py#L76-L81

https://github.com/opensafely/cohort-extractor/blob/1d3d53545c1eb06caad3ed4993eb483907417062/cohortextractor/study_definition.py#L297-L299

To avoid confusion (as in #235) we should either accept this everywhere we accept a date or, my preference, stop accepting it at all. In general I don't like the non-determinism it brings.

**Comment by sebbacon** [comment]
Agreed to non-determinism.

Adding a required "index date" argument for when the function is called is a reasonable option?

**Comment by evansd** [comment]
As of #255, `today` is now supported everywhere. But there's still an open question as to whether we want to support it at all.

**Comment by sebbacon** [comment]
No we shouldn't. See #374
