### ISSUE TITLE
Clarification about structure and format of APCS.Diagnosis_Der_All

### ISSUE THREAD

**Issue by inglesp** [opensafely/cohort-extractor#256]
From the [sample of dummy data], and from looking at a selection of values on the server, it's not clear exactly how `Diagnosis_Der_All` is formatted in the `APCS` table.

It seems to contain many 4- or 5-digit alphanumeric codes, separated by a combination of whitespace, commas, and double pipes (`||`).

So:

* What are these alphanumeric codes, and how do they correspond to ICD-10 codes, which contain dots?
* What do the double pipes signify?
* Given a list of ICD-10 codes or ICD-10 prefixes, what's the best way in SQL to filter rows that match any of the codes/prefixes?

**Comment by krishnanbhaskaran** [comment]
>What are these alphanumeric codes, and how do they correspond to ICD-10 codes, which contain dots?

I'm certain that these are ICD10 codes with the dot after the third character simply removed. Your sample row on Slack was

I801 ,I802 ,N179 ,N183 ,C61X ,I489 ,I259 ,I10X ,E119 ,E780 ,J849 ,K869 ,M069 ,Z824 ,Z867 ,Z915 ||I801 ,I802 ,N179 ,N183 ,C61X ,I489 ,I259 ,I10X ,E119 ,E780 ,J849 ,K869 ,M069 ,Z824 ,Z867 ,Z915 ||I801 ,I802 ,N179 ,N183 ,C61X ,I489 ,I259 ,I10X ,E119 ,E780 ,J849 ,K869 ,M069 ,Z824 ,Z867 ,Z915 

so these are the codes 
I80.1 (Phlebitis and thrombophlebitis of femoral vein)
I80.2 (Phlebitis and thrombophlebitis of other deep vessels of lower extremities)
N17.9 (Acute renal failure, unspecified) 
and so on.

In fact code lists can also be supplied without the dot (as was done for the COVID-19 ICD code list used against the ONS data (https://codelists.opensafely.org/codelist/opensafely/covid-identification/2020-06-03/#full-list) so I think we can safely ignore the dots issue.

>What do the double pipes signify?

Not clear, but something I noticed in your example row is that after each double pipe there is simply a repeat of the whole list - not sure if this is always the case?

I801 ,I802 ,N179 ,N183 ,C61X ,I489 ,I259 ,I10X ,E119 ,E780 ,J849 ,K869 ,M069 ,Z824 ,Z867 ,Z915 
||I801 ,I802 ,N179 ,N183 ,C61X ,I489 ,I259 ,I10X ,E119 ,E780 ,J849 ,K869 ,M069 ,Z824 ,Z867 ,Z915 
||I801 ,I802 ,N179 ,N183 ,C61X ,I489 ,I259 ,I10X ,E119 ,E780 ,J849 ,K869 ,M069 ,Z824 ,Z867 ,Z915


> Given a list of ICD-10 codes or ICD-10 prefixes, what's the best way in SQL to filter rows that match any of the codes/prefixes?

I don't know sql but would say the desired behaviour is that you search for anything starting with the code specified. e.g. if I'm searching for all acute renal failure, I would specify N17 in the code list. The code would then search for any codes starting with N17 (is this N17% in SQL?) and would thus pick up the N179 code above.

**Comment by sebbacon** [comment]
@inglesp what is the next action on this? thanks.

**Comment by inglesp** [comment]
Closing.  We understand the structure of the data, and haven't need to answer "what's the best way in SQL to filter rows that match any of the codes/prefixes?".
