### ISSUE TITLE
run cohort extractor on a single study_definition

### ISSUE THREAD

**Issue by wjchulme** [opensafely/cohort-extractor#259]
When there are multiple study definitions in a repo, `generate_cohort` will create a study cohort for all definitions each time it is run. Often only one definition has been updated, so cohort extractor may take a long time even if you only need to update one cohort. It would be useful if you could run just one definition (or a subset of definitions) at a time. 

Main use for this is so that I can have a single repo containing a suite of notebooks, each of which may use a small number of study cohorts. Sometimes I may only want to update the cohorts that are used by a specific notebook. I'm sure this would be useful for proper research repos too.

__Option 1__ is a manual option like 

    cohortextractor generate_cohort --definition study_definition_1 study_defintion_2 --database-url ...

but the danger with this is that you could accidentally not update a cohort to match a recently updated definition, and it it may go completely unnoticed and trip people up. So maybe it should come with at least a warning.

__Option 2__ is to save a hash of the study definitions each time `cohortextractor` is run, and then the next time it runs it checks the hashes to make sure there has been a change before extracting each cohort. It would also need to check the codelists haven't been updated, and if there's been a new database build since the last run. Then updates would happen only if changes were detected. You could force it to update if you wanted to with a command option (or by deleting the saves hashes).

**Comment by alexwalkercebm** [comment]
Yes I agree that this is a good idea. The workaround I've been using so far is renaming the study definitions on the server to stop them getting picked up. The manual option (1) sounds okay to me if it's easier. If the default was to run all definitions, then that should negate most of the risk of forgetting to update one, because to run anything other than all of them you'd have to explicitly say so.

**Comment by wjchulme** [comment]
Sounds good. Hash option might be something to keep in mind in case one day too many extracts start to slow things down

**Comment by alexwalkercebm** [comment]
Yes would be nice for it to be automated. Would presumably work in a similar way to the query caching in the `datalab-pandas` library [here](https://github.com/ebmdatalab/datalab-pandas/blob/9356a8a0d99d35ce4794a6a73c0465dc69b22a7e/ebmdatalab/bq.py#L11-L24).
