### ISSUE TITLE
Query primary care date of death

### ISSUE THREAD

**Issue by alexwalkercebm** [opensafely/cohort-extractor#263]
As we only have ONS death data for a limited period, and we think that fact and date (but not cause) of death are reasonably accurately recorded in primary care, we would like to be able to return the date of death from primary care records. This looks to be just the `DateOfDeath` from the `Patient` table, though it looks from the dummy schema that this is recorded as `9999-12-01` for patients who are alive.
![github com_opensafely_tpp-sql-notebook_blob_master_notebooks_tpp-schema ipynb](https://user-images.githubusercontent.com/24895935/89318979-70ca9b80-d677-11ea-8aa2-86fcddadc159.png)

**Comment by evansd** [comment]
@alexwalkercebm Just thinking about naming this. We already have `with_death_recorded_in_cpns`. Would `with_death_recorded_in_gp_record` be OK? I dislike the repetition of "record" but I can't immediately think of a better alternative?

**Comment by alexwalkercebm** [comment]
Or if you want to avoid repetition, `with_death_recorded_in_primary_care`? Either is fine I think. There's also `patients.died_from_any_cause` and `patients.with_these_codes_on_death_certificate` for deaths recorded in ONS, but they relate to cause, so fine to use a different naming scheme.
