### ISSUE TITLE
Get MixedSoftwareHousehold variable through Study Definition

### ISSUE THREAD

**Issue by annaschultze** [opensafely/cohort-extractor#285]
For the care-homes mortality project, we're looking to exclude care homes which are mixed software using the MixedSoftwareHousehold variable I understand Jonny has created. Is it possible to write a function I can use in the study_definition so this can be added to my input.csv file?

**Comment by wjchulme** [comment]
Household info is wrapped up in one extractor function, `patients.household_as_of()`, which is [here](https://github.com/opensafely/cohort-extractor/blob/da036416bbb2f55bb4fbbca1b791acdf16f0f2d1/cohortextractor/tpp_backend.py#L1436). I think this is just a case of adding an option for `returning = "is_mixed"` to this function (or something more verbose like `returning = "is_mixed_EHR_software"`). If so, I think we just need to add
```
    elif returning == "is_mixed":
                column = "CASE Household.MixedSoftwareHousehold WHEN 'TRUE' THEN 1 ELSE 0 END"
```
to the `returning` logic, plus tests.

**Comment by sebbacon** [comment]
Something to note in passing  - we've not talked about implementing household algorithms at all with EMIS yet - so don't count on this being available cross-backend any time soon.
