### ISSUE TITLE
Variable "as of" dates in study definitions

### ISSUE THREAD

**Issue by alexwalkercebm** [opensafely/cohort-extractor#347]
>An additional issue that may need resolving is having more flexibility for "as of" dates. Currently we can ask for example "what's the patient's care home status as of <index_date>", where index date is a scalar fixed across all patients. But we can't ask "what's the patient's care home status as of <hosp_admission_date>", i.e., for vectorised dates.
>
>You'd want this for both one-row-per-patient datasets and one-row-per-event datasets. It would probably need a table of "state transition" dates (care home status, dialysis status, employment status, whatever) to implement
>
>_Originally posted by @wjchulme in https://github.com/opensafely/cohort-extractor/issues/136#issuecomment-726039157_

I think this is distinct and important enough to have its own issue. It's also somewhat urgent, as the lack of this is meaning that some current studies are having to use an awkward and imperfect workaround of defining a variable many times within monthly windows, then piecing those back together subsequently to get a more complete picture of when a thing happened. For example:
 - @StatsFizz's smoking status and bmi in [Risk Prediction](https://github.com/opensafely/risk-prediction-research/blob/db8be510860854c6029cbb472abac4ddba919f8e/analysis/study_definition.py#L243)
 - @angelwong121's drug exposures in [anticoagulants](https://github.com/opensafely/anticoagulants-research/blob/13dcfa0c8ed76eb200dce7cd30d75e26471ac7a3/analysis/common_variables.py#L135)
 - My and @johntaz's outcomes in the thrombosis after COVID ([here](https://github.com/opensafely/post-covid-thrombosis-research) but not yet coded), where we need to determine whether an outcome occurred both before and after the patient index date, but that index date is not fixed (it's the date when a patient was discharged from hospital).
 - Any of the other near future outcomes after COVID study.
 - Any vaccine follow-up studies (which we might have to implement quickly when asked by external people)

While this could be determined using a time varying separate dataset for these variables as described in #136, it's then extracting more data than needed, and is more awkward to code downstream then just being able to do e.g. `on_or_after=list_of_individual_patient_index_dates`. 

cc @DarthCTR and @sebbacon as you also commented on #136.

**Comment by alexwalkercebm** [comment]
Here's a simplified example study definition that uses two date columns defined within the study definition as `between` dates for another variable.
https://github.com/opensafely/post-covid-thrombosis-research/blob/331a8e81c464debd58a388c86c26e21c72d6ee51/analysis/study_definition_dynamic_index_date.py

```py
from cohortextractor import (
    StudyDefinition,
    patients,
    codelist,
    codelist_from_csv,
    combine_codelists,
)
from codelists import *


start_date = "2020-02-01"

study = StudyDefinition(
    default_expectations={
        "date": {"earliest": "1900-01-01", "latest": "today"},
        "rate": "exponential_increase",
        "incidence": 0.7,
    },
    population=patients.satisfying(
        """
            has_follow_up
        AND admission_date
        """,
        has_follow_up=patients.registered_with_one_practice_between(
            "2019-02-01", "2020-02-01"
        ),
    ),
    admission_date=patients.admitted_to_hospital(
        returning="date_admitted",
        with_these_diagnoses=covid_codelist,
        on_or_after=start_date,
        date_format="YYYY-MM-DD",
        find_first_match_in_period=True,
        return_expectations={"date": {"earliest": start_date}},
    ),
    discharge_date=patients.admitted_to_hospital(
        returning="date_discharged",
        with_these_diagnoses=covid_codelist,
        on_or_after=start_date,
        date_format="YYYY-MM-DD",
        find_first_match_in_period=True,
        return_expectations={"date": {"earliest": start_date}},
    ),
    stroke_gp=patients.with_these_clinical_events(
        stroke,
        return_first_date_in_period=True,
        date_format="YYYY-MM-DD",
        between=[admission_date, discharge_date],
        return_expectations={
            "date": {"earliest": admission_date, "latest": discharge_date}
        },
    ),
)
```

**Comment by alexwalkercebm** [comment]
In terms of passing an external vector of dates (rather than using a variable defined in the study definition), I was thinking that this could be similar to the way we import codelists into the db?

```py
from cohortextractor import index_dates_from_csv

admission_date = index_dates_from_csv(
    "index_dates/covid-admission-dates.csv",
    patient_id_column="patient_id",
    index_date_column="admission_date",
)

**Comment by DarthCTR** [comment]
@alexwalkercebm Assuming that start_date in your code is the variable that would hold the vector of baseline dates, I would expect this to impact the has_follow_up filter as well: 

```
        has_follow_up=patients.registered_with_one_practice_between(
            start_date-365, start_date
        ),
```

**Comment by alexwalkercebm** [comment]
@DarthCTR In this case `start_date` is just a fixed date `"2020-02-01"`, which is defined near the top.

**Comment by DarthCTR** [comment]
@alexwalkercebm Okay. So start_date is start of study period. Then, in your example, we want to look for first hospitalisation that occurred after start_date, and among those, identify whether patients had a stroke diagnosis during that first hospitalisation.  

With that understanding, I'll amend the example for looking back in time from the vector of baseline dates:

```
    hypertension=patients.with_these_clinical_events(
        hypertension_codes,
        between=[admission_date-180, admission_date],
        return_first_date_in_period=True,
        include_month=True,
        return_expectations={"date": {"earliest": admission_date}},
    ),
```

**Comment by alexwalkercebm** [comment]
Incidentally, elsewhere in that repo I've already written a little custom `days_before` function for fixed dates. Like [here](https://github.com/opensafely/post-covid-thrombosis-research/blob/331a8e81c464debd58a388c86c26e21c72d6ee51/analysis/common_variables.py#L6-L9).
```py
def days_before(s, days):
    date = datetime.strptime(s, "%Y-%m-%d")
    modified_date = date - timedelta(days=days)
    return datetime.strftime(modified_date, "%Y-%m-%d")
```
