### ISSUE TITLE
What's up with Dave's `black`?

### ISSUE THREAD

**Issue by evansd** [opensafely/cohort-extractor#367]
When I run `black` locally using the latest version `v20.8b1` with no special configuration it wants to reformat a significant proportion of the codebase. Many of the changes seem to be undoing this "Blacken code" commit: https://github.com/opensafely/cohort-extractor/commit/e209cecc176c6e24f4f7c61a4af62df72abbfe7b 

We should add `black` to the dev requirements and ensure that any custom configuration (which we shouldn't really need anyway) lives in `pyproject.toml`. But before I do that I want to figure out what's happened here so it doesn't happen again.

Any idea @sebbacon?

**Comment by madwort** [comment]
I /think/ I've seen black do this due to mismatched minor python revision (i.e. 3.5 vs 3.9) - which version were you using? (& which version is @sebbacon using...?)

**Comment by evansd** [comment]
Good point. I'm running `Python 3.7.9` in that venv.

**Comment by sebbacon** [comment]
I'm running `3.7.7`...

**Comment by sebbacon** [comment]
Ah, I have a theory that it's related to my VS Code settings. Turns out you have to manually select your interpreter on each new folder open. I *think* this was not a stick setting. Will investigate more...

**Comment by sebbacon** [comment]
Making notes here.

Add pythonPath as the output of `pyenv which python`, thus:

```json
{
    "python.pythonPath": "/home/seb/.pyenv/versions/3.7.7/envs/cohort-extractor/bin/python"
}
```

**Comment by sebbacon** [comment]
To summarise, I am using `black` version `20.8b1` and python 3.7.7, and _one_ file (`patients.py`) has new formatting changes on currently code (which, incidentally, we actually don't want, but that's another story)

**Comment by evansd** [comment]
So it turns out the problem is on my end, though I still don't know what on earth has happened:
```
dave@carnap:~/projects/ebmdatalab/cohort-extractor$ pip freeze | grep black
black==20.8b1

dave@carnap:~/projects/ebmdatalab/cohort-extractor$ black --version
black, version 19.10b0

dave@carnap:~/projects/ebmdatalab/cohort-extractor$ which black
/home/dave/.virtualenvs/ebm-cohort-extractor/bin/black
```

**Comment by evansd** [comment]
The answer was that bash had [cached](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/hash.html) the lookup for `black` to point to an old user-wide install of Black rather than the virtualenv. Running `which black` gave me a path in the virtualenv as expected, but this did not match what got executed when I ran `black`.

Running `hash -r` cleared this cache and then everything worked as expected.
