### ISSUE TITLE
Return dates from combined variables

### ISSUE THREAD

**Issue by alexwalkercebm** [opensafely/cohort-extractor#399]
It would be convenient to be able to combine dates from different variables into one. While use cases involving one data source would almost always be better served by combining codelists and just running a separate combined query, this is not possible when looking for events in different tables.

For example, if we were looking for stroke as an outcome event, we might define this as the earliest event occurring in either GP or hospital:
```py
    stroke_gp=patients.with_these_clinical_events(
        stroke_codes,
        return_first_date_in_period=True,
        date_format="YYYY-MM-DD",
        on_or_after="index_date",
        return_expectations={"date": {"earliest": "exposure_discharge"}},
    ),
    stroke_hospital=patients.admitted_to_hospital(
        with_these_diagnoses=stroke_codes_icd_10,
        returning="date_admitted",
        find_first_match_in_period=True,
        date_format="YYYY-MM-DD",
        on_or_after="index_date",
        return_expectations={"date": {"earliest": start_date}},
    ),
```
Which we'd then like to combine:
```py
    stroke=patients.earliest_of_these_dates(["stroke_gp", "stroke_hospital"])
```

While we can already combine variables to produce binary or categorical variables (though not currently using dates, see https://github.com/opensafely/cohort-extractor/issues/329), there are situations (as above) where a date needs to be returned - in a cohort study the outcome date is needed to determine the amount of follow-up time between the start and the outcome.

**Comment by evansd** [comment]
On my phone at the moment so can't easily dig out the documentation link, but I'm pretty sure this is already covered by `minimum_of`and  `maximum_of` which are designed to handle dates too.

**Comment by alexwalkercebm** [comment]
Oh, magic, looks like they do exactly what I was intending!
