### ISSUE TITLE
Query the Vaccination table

### ISSUE THREAD

**Issue by alexwalkerepi** [opensafely/cohort-extractor#82]
We need to be able to query the `Vaccination` table. I'd guess this should be analogous to querying `CodedEvent` or `MedicationIssue`, only with a list of `VaccinationName_ID`.

Brian made a notebook to identify the flu vaccine IDs https://github.com/ebmdatalab/tpp-sql-notebook/blob/BMK-vacc-test/notebooks/vacc.ref.ipynb

## Vaccination
 Patient_ID | Vaccination_ID | VaccinationDate | VaccinationName | VaccinationName_ID | VaccinationSchedulePart
-- | -- | -- | -- | -- | --
3 | 339777 | 2015-06-02 11:54:34 | Mumps | 58 | 1
3 | 339776 | 2015-06-02 11:34:14 | DTP + Polio | 192 | 1
3 | 386215 | 2015-07-14 10:40:38 | dTP | 2573 | 2
3 | 386225 | 2015-07-09 16:48:38 | Menjugate (Babies 2-4 months) | 132 | 1
23 | 319247 | 2019-04-08 11:11:55 | HNIG | 190 | 1

## VaccinationReference

VaccinationName_ID | VaccinationName | VaccinationContent
-- | -- | --
1 | Typhim VI - Single Dose | TYPHOID
2 | Hepatyrix | TYPHOID
2 | Hepatyrix | HEPATITIS A
3 | Typherix - Single Dose | TYPHOID
4 | Infant BCG | BCG

**Comment by evansd** [comment]
The possible values for `VaccinationSchedulePart` are (from the `DataDictionary` table):

Table | Type | Code | Description
-- | -- | -- | --
Vaccination | VaccinationSchedulePart | 1 | 1
Vaccination | VaccinationSchedulePart | 2 | 2
Vaccination | VaccinationSchedulePart | 3 | 3
Vaccination | VaccinationSchedulePart | 4 | Single
Vaccination | VaccinationSchedulePart | 5 | Booster 1
Vaccination | VaccinationSchedulePart | 6 | Booster 2
Vaccination | VaccinationSchedulePart | 7 | Reinforcing
Vaccination | VaccinationSchedulePart | 8 | 4
Vaccination | VaccinationSchedulePart | 9 | Booster
Vaccination | VaccinationSchedulePart | 10 | Adolescent Booster 1
Vaccination | VaccinationSchedulePart | 12 | Adolescent Booster 2
Vaccination | VaccinationSchedulePart | 13 | Part 1 Under 12 Months

**Comment by brianmackenna** [comment]
| Table | Detail |
|--|--|
|VaccinationName_ID|Is this standard?|
|VaccinationName| Product name in TPP dictionary. Generics and brand prescribing appear|
|VaccinationDate|Month and time|
|VaccinationSchedulePart|As above - indication where something falls in the routine vaccination schedule|
|VaccinationContent|The disease/pathogen that is being vaccinated against|

**Comment by evansd** [comment]
I'm almost 100% certain that VaccinationName_ID is just an internal thing and not a standard code.

With `VaccinationName`, can we map this to something standard that we can match a codelist against?

For `VaccinationContent` is this using anything standard for pathogen names that we can match against?

In general, whenever we see strings in database fields we want to know what set of possible strings these are drawn from.

**Comment by brianmackenna** [comment]
- `VaccinationName_ID` or `Vaccination_ID` could be multilex? Pretty sure both internal but good to confirm with @chris-tpp 

- Re codelist matching -> I have created [csv file/codelist](https://github.com/ebmdatalab/vaccinations-covid-codelist-notebook/blob/master/notebooks/Pneumococcal.ipynb) from the vaccination ref table here to put on to OpenCODELISTS (there is currently a bug preventing loading that Peter is on and will fix). Does this work @evansd?   

- `VaccinationContent` Pretty sure it isn't standard. (mainly due to presence of the pathogen `'Mikes Content'`)

**Comment by evansd** [comment]
Right. I've got the answer here. The table and all the values within it are proprietary TPP stuff. They need a system to track childhood imms very accurately and so don't rely on the standard read code events table for this.

That's all fine. We just need to make sure the API reflects this.
